#!/bin/bash
set -e
cd /tmp/

echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories

apk add --update --no-cache bind-tools curl 

curl -sSL https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-amd64.tar.gz | tar xfz - -C /

rm -rf /tmp/* /var/tmp/* /var/cache/apk/*