image: docker:latest

services:
  - docker:dind

# ---------------------------------------
# Global
# ---------------------------------------

stages:
  - Build
  - Test
  - Deploy

variables:
  STAGING_REGISTRY: registry.gitlab.com
  STAGING_NAMESPACE: jrbeverly
  STAGING_PROJECT: docker-alpine

  REGISTRY: docker.io
  NAMESPACE: jrbeverly
  PROJECT: alpine

  GIT_COMMIT: ${CI_COMMIT_SHA}
  TAG_PREFIX: ${CI_PIPELINE_ID}-

# ----------------------------------------
# Prescript
# ----------------------------------------

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $STAGING_REGISTRY
  - apk --update-cache add make

# ----------------------------------------
# Build
# ----------------------------------------

build-edge:
  stage: Build
  variables:
    VERSION: edge
  script:
    - make -C build/ build
    - make -C build/ push
  only:
    - web
    - contrib
    - master

# ----------------------------------------
# Tests
# ----------------------------------------

test-edge:
  stage: Test
  variables:
    VERSION: edge
  script:
    - make -s -C build/ pull
    - make -s -C build/ test
  dependencies:
    - build-edge
  only:
    - web
    - contrib
    - master

# ----------------------------------------
# Deploy
# ----------------------------------------

deploy:
  stage: Deploy
  script:
    - sh build/ci/pull.sh
    - docker login -u $DOCKER_BUILD_USER -p $DOCKER_BUILD_TOKEN
    - sh build/ci/deploy.sh
  dependencies:
    - test-edge
  only:
    - web
    - contrib
    - master