image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com 

variables:
  CONTAINER_REGISTRY: registry.gitlab.com

stages:
  - build
  - test
  - release

build:
  stage: build
  script:
    - cd build/ && sh docker-make make $CONTAINER_REGISTRY $CI_PROJECT_NAMESPACE $CI_PROJECT_NAME $CI_BUILD_ID && sh docker-make deploy
  only:
    - master
  artifacts:
    paths:
      - build/.build/

test:
  stage: test
  script:
    - cd build/ && sh docker-make pull && sh docker-make test
  dependencies:
    - build
  only:
    - master
  artifacts:
    paths:
      - build/.build/

release:
  stage: release
  script:
    - docker login -u $DOCKER_BUILD_USER -p $DOCKER_BUILD_TOKEN
    - cd build/ && cd build/ && sh docker-make pull && sh docker-make release
  dependencies:
    - build
  only:
    - master