FROM alpine:3.4

# 
# Environment Variables
#
ENV HOME=/

#
# Build Arguments
#
ARG S6_OVERLAY_URL

# 
# Provision
#
COPY provision/install.sh /tmp/install.sh
RUN sh /tmp/install.sh && rm -f /tmp/install.sh

COPY rootfs/ /

# 
# Options
#
ENTRYPOINT ["/init"]
CMD []

#
# Metadata Arguments
#
ARG BUILD_DATE
ARG VERSION
ARG VCS_REF

#
# Metadata
#
LABEL \
    maintainer="jrbeverly" \
    \
    org.label-schema.name="appimage" \
    org.label-schema.summary="A minimal Docker image based on Alpine Linux designed for applications." \
    org.label-schema.description="A minimal Docker image based on Alpine Linux designed for applications." \
    org.label-schema.maintainer="jrbeverly" \
    org.label-schema.build-date=$BUILD_DATE \
    org.label-schema.version=$VERSION \
    org.label-schema.url="" \
    org.label-schema.license="MIT" \
    org.label-schema.vcs-type="Git" \
    org.label-schema.vcs-ref=$VCS_REF \
    org.label-schema.vcs-url="https://gitlab.com/jrbeverly-docker/docker-alpine.git" \
    org.label-schema.docker.cmd="docker run -it -v $(pwd):/media/ jrbeverly/appimage:alpine sh" \
    org.label-schema.vendor="jrbeverly" \
    org.label-schema.schema-version="1.0" \
    \
    io.jrbeverly.user=$DUID \
    io.jrbeverly.group=$DGID \
    io.jrbeverly.project="appimage" \
    io.jrbeverly.summary="A minimal Docker image based on alpine:edge designed for applications." \
    io.jrbeverly.appimage.meta.BUILD_DATE="The Date/Time the image was built." \
    io.jrbeverly.appimage.meta.VERSION="Release identifier for the contents of the image." \
    io.jrbeverly.appimage.meta.VCS_REF="Identifier for the version of the source code from which this image was built." \
    io.jrbeverly.appimage.args.S6_OVERLAY_URL="The [S6 Overlay](https://github.com/just-containers/s6-overlay/releases) URL download for containers."